// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment("ANDROID_FIREBASE_API_KEY"),
    appId: String.fromEnvironment("ANDROID_FIREBASE_API_ID"),
    messagingSenderId: '923070414802',
    projectId: 'flowiq-edd9d',
    storageBucket: 'flowiq-edd9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment("IOS_FIREBASE_API_KEY"),
    appId: String.fromEnvironment("IOS_FIREBASE_API_ID"),
    messagingSenderId: '923070414802',
    projectId: 'flowiq-edd9d',
    storageBucket: 'flowiq-edd9d.firebasestorage.app',
    iosBundleId: 'com.example.flowiq.flowiq',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment("WEB_FIREBASE_API_KEY"),
    appId: String.fromEnvironment("WEB_FIREBASE_API_ID"),
    messagingSenderId: '923070414802',
    projectId: 'flowiq-edd9d',
    authDomain: 'flowiq-edd9d.firebaseapp.com',
    storageBucket: 'flowiq-edd9d.firebasestorage.app',
    measurementId: 'G-WK0QX1CVSE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment("MACOS_FIREBASE_API_KEY"),
    appId: String.fromEnvironment("MACOS_FIREBASE_API_ID"),
    messagingSenderId: '923070414802',
    projectId: 'flowiq-edd9d',
    storageBucket: 'flowiq-edd9d.firebasestorage.app',
    iosBundleId: 'com.example.flowiq.flowiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment("WINDOWS_FIREBASE_API_KEY"),
    appId: String.fromEnvironment("WINDOWS_FIREBASE_API_ID"),
    messagingSenderId: '923070414802',
    projectId: 'flowiq-edd9d',
    authDomain: 'flowiq-edd9d.firebaseapp.com',
    storageBucket: 'flowiq-edd9d.firebasestorage.app',
    measurementId: 'G-5RN92Q9XY0',
  );

}